### ISSUE TITLE
Splatoon 3 Tag byml crashes the tool

### ISSUE THREAD

**Issue by nacho95101** [ArchLeaders/TotkTagEditor#1]
With the recent 9.0.0 Splatoon 3 update, the tool won't open the Tag byml file anymore. It'll crash upon loading it and close inmediatly with no error output or similar.

[[Tag.Product.900.rstbl.byml.zs](https://cdn.discordapp.com/attachments/1246015463201443845/1280223823093956749/Tag.Product.900.rstbl.byml.zs?ex=66d74cd8&is=66d5fb58&hm=d14ab468e1a55ef3e54da32416a96818d8e2c1b62af704d8efe83555e7aedc7b&)](https://cdn.discordapp.com/attachments/1246015463201443845/1280223823093956749/Tag.Product.900.rstbl.byml.zs?ex=66d74cd8&is=66d5fb58&hm=d14ab468e1a55ef3e54da32416a96818d8e2c1b62af704d8efe83555e7aedc7b&)

**Comment by ArchLeaders** [comment]
The BitTable format is slightly different. However, I might be able to implement it if you have a specification.

**Comment by nacho95101** [comment]
I don’t really know what that means but anything that can make the file be editable again would be awesome 😅

**Comment by ArchLeaders** [comment]
Fixed in [v1.1.1](https://github.com/ArchLeaders/TotkTagEditor/releases/tag/v1.1.1)
